import {
  UserIcon,
  Door01Icon,
  ServiceIcon,
  DatabaseIcon,
  LayerIcon,
  Notification01Icon,
  FolderFileStorageIcon,
  CloudIcon,
  ServerStack01Icon,
  MailQuestionMarkIcon,
} from "@hugeicons/core-free-icons"
import type { ArchitectureNodeKind, NodeStyle } from "./types"

export const nodeIcons: Record<ArchitectureNodeKind, typeof UserIcon> = {
  client: UserIcon,
  gateway: Door01Icon,
  service: ServiceIcon,
  database: DatabaseIcon,
  cache: LayerIcon,
  queue: Notification01Icon,
  storage: FolderFileStorageIcon,
  external: CloudIcon,
  infrastructure: ServerStack01Icon,
  generic: MailQuestionMarkIcon,
}

export const nodeTheme: Record<ArchitectureNodeKind, NodeStyle> = {
  client: {
    border: "border-blue-600",
    badge: "border-blue-500 text-blue-700",
    selectedShadow: "shadow-lg shadow-blue-400",
    hoverShadow: "shadow-lg hover:shadow-blue-300",
    iconClass: "size-5 text-blue-600",
    iconBackground: "bg-blue-100",
  },
  gateway: {
    border: "border-purple-600",
    badge: "border-purple-500 text-purple-700",
    selectedShadow: "shadow-lg shadow-purple-400",
    hoverShadow: "shadow-lg hover:shadow-purple-300",
    iconClass: "size-5 text-purple-600",
    iconBackground: "bg-purple-100",
  },
  service: {
    border: "border-slate-600",
    badge: "border-slate-500 text-slate-700",
    selectedShadow: "shadow-lg shadow-slate-400",
    hoverShadow: "shadow-lg hover:shadow-slate-300",
    iconClass: "size-5 text-slate-600",
    iconBackground: "bg-slate-100",
  },
  database: {
    border: "border-green-600",
    badge: "border-green-500 text-green-700",
    selectedShadow: "shadow-lg shadow-green-400",
    hoverShadow: "shadow-lg hover:shadow-green-300",
    iconClass: "size-5 text-green-600",
    iconBackground: "bg-green-100",
  },
  cache: {
    border: "border-orange-600",
    badge: "border-orange-500 text-orange-700",
    selectedShadow: "shadow-lg shadow-orange-400",
    hoverShadow: "shadow-lg hover:shadow-orange-300",
    iconClass: "size-5 text-orange-600",
    iconBackground: "bg-orange-100",
  },
  queue: {
    border: "border-amber-600",
    badge: "border-amber-500 text-amber-700",
    selectedShadow: "shadow-lg shadow-amber-400",
    hoverShadow: "shadow-lg hover:shadow-amber-300",
    iconClass: "size-5 text-amber-600",
    iconBackground: "bg-amber-100",
  },
  storage: {
    border: "border-olive-600",
    badge: "border-olive-500 text-olive-700",
    selectedShadow: "shadow-lg shadow-olive-400",
    hoverShadow: "shadow-lg hover:shadow-olive-300",
    iconClass: "size-5 text-olive-600",
    iconBackground: "bg-olive-100",
  },
  external: {
    border: "border-cyan-600",
    badge: "border-cyan-500 text-cyan-700",
    selectedShadow: "shadow-lg shadow-cyan-400",
    hoverShadow: "shadow-lg hover:shadow-cyan-300",
    iconClass: "size-5 text-cyan-600",
    iconBackground: "bg-cyan-100",
  },
  infrastructure: {
    border: "border-red-600",
    badge: "border-red-500 text-red-700",
    selectedShadow: "shadow-lg shadow-red-400",
    hoverShadow: "shadow-lg hover:shadow-red-300",
    iconClass: "size-5 text-red-600",
    iconBackground: "bg-red-100",
  },
  generic: {
    border: "border-2 border-dashed border-gray-600",
    badge: "border-gray-500 text-gray-700",
    selectedShadow: "shadow-lg shadow-gray-400",
    hoverShadow: "shadow-lg hover:shadow-gray-300",
    iconClass: "size-5 text-gray-600",
    iconBackground: "bg-gray-100",
  },
}
